services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CI_DB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  php:
    build: ./
    container_name: php-apache
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./CI4:/var/www/html
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  redis_data:
